library(IMS3)
set.enviroment()
setwd("/home/rstudio")
message("Downloading files")
aws.s3::s3sync(bucket = "ignacios-test-bucket", direction = "download")
message("Rendering markdown")
rmarkdown::render(input = "./example.Rmd")
message("Uploading files")
aws.s3::put_object("./example.html", bucket = "ignacios-test-bucket", object = "example.html")
message("Cleaning up")
file.remove("example.Rmd", "example.html")
message("Done!")
